name: df_debug_wrapper
description: "Development tool that overlays a customizable banner on its child widget."

version: 1.0.0

homepage: https://dartforce.dev/
repository: https://github.com/DartForce22/df_dropdown.git
license: MIT

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
